name: Create issue on pull request
on: pull_request

jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/create-an-issue@v2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB }}

